<?php include 'parts/top-bar.php'; ?>
<?php include 'parts/header.php'; ?>
<?php include 'parts/frontpage/landing.php'; ?>
<?php include 'parts/frontpage/software-features.php'; ?>
<?php include 'parts/frontpage/solutions.php'; ?>
<?php include 'parts/frontpage/services.php'; ?>
<?php include 'parts/frontpage/customers.php'; ?>
<?php include 'parts/frontpage/events.php'; ?>
<?php include 'parts/frontpage/bottom-resources.php'; ?>
<?php include 'parts/frontpage/book-demo.php'; ?>
<?php include 'parts/footer.php'; ?>